Dev leon 2
iolite312/Project-2.1 pull request #14
Opened 2024-10-27 10:14 UTC by iolite312

2024-10-27 15:09 UTC, Toast3347 commented on Api/Controllers/AuthController.cs
> +    }
Deze methode moet kleiner, je kan het misschien in meerdere methods verdelen.

2024-10-27 15:11 UTC, Toast3347 commented on Api/Swagger/ConfigureSwaggerOptions.cs
> +        }
Als het kan deze ook graag kleiner maken.

2024-10-27 15:14 UTC, Toast3347 commented on DAL/EmployeeDAO.cs
>          public void UpdateEmployee(Employee employee)
Deze ook graag kleiner maken.

2024-10-27 15:21 UTC, Toast3347 requested changes
Ziet er goed uit alleen moeten een paar methods kleiner gemaakt worden.

2024-10-30 10:53 UTC, iolite312 commented on Api/Swagger/ConfigureSwaggerOptions.cs
> +        }
deze gaat niet vanwege hoe de interface van swagger inheritance doet

2024-10-30 11:52 UTC, Toast3347 approved these changes
Molto bene

2024-10-30 11:53 UTC, merged