Dev jayden
iolite312/Project-2.1 pull request #9
Opened 2024-10-15 20:04 UTC by JaydenVanKlooster

klaar volgens trello

2024-10-15 20:14 UTC, Toast3347 commented on DAL/DashboardDAO.cs
> +            return tickets.Count;
Dit kan in een methode in de service. 
List<Ticket> tickets = GetTicketsFromDatabase();
int openTicketCount = tickets.Count(ticket => ticket.Status == "open");
int ticketCount = tickets.Count();

2024-10-15 20:14 UTC, Toast3347 commented on Logic/DashboardService.cs
> +        }
Zelfde als vorige comment
List<Ticket> tickets = GetTicketsFromDatabase();
int openTicketCount = tickets.Count(ticket => ticket.Status == "open");
int ticketCount = tickets.Count();

2024-10-15 20:22 UTC, Toast3347 requested changes
De ticket count methodes naar de db zijn overbodig. vgm doe je dit ook al met methods in je dashboard.cs. i.p.v een query naar de db uit te voeren. De rest ziet er top uit!

2024-10-16 06:27 UTC, iolite312 reviewed
Misschien moeten we samen nog even kijken naar de functions in het dashboard form maar voor de rest geloof ik het wel en ja dat puntje van jasper nog even doen

2024-10-16 08:22 UTC, Toast3347 approved these changes
Muchos buenos

2024-10-16 08:23 UTC, merged